import { HeroSection } from "@/features/gravityteam/hero-section";
import { Navigation } from "@/features/gravityteam/navigation";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import "./styles.css";
import { AboutGravityTeam } from "@/features/gravityteam/about-gravity-team";
import { CryptoMarkerMaking } from "@/features/gravityteam/crypto-market-making";
import { OurPartnersAndFriends } from "@/features/gravityteam/our-partners-and-friends";
import { JoinGravityTeam } from "@/features/gravityteam/join-gravity-team";
import { Footer } from "@/features/gravityteam/footer";
import { ContactUs } from "@/features/gravityteam/contact-us";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function GravityTeamPage() {
  return <div className={cn("bg-[#141619] font-normal", inter.className)}>
    <Navigation/>
    <HeroSection/>
    <AboutGravityTeam/>
    <CryptoMarkerMaking/>
    <OurPartnersAndFriends/>
    <JoinGravityTeam/>
    <ContactUs/>
    <Footer/>
  </div>;
}
